// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJEc6XsOC3raC7K2UravUJMuYmBJvS3iY',
    appId: '1:525477025365:web:e84ee550b52c2f84c826dc',
    messagingSenderId: '525477025365',
    projectId: 'autofore-app',
    authDomain: 'autofore-app.firebaseapp.com',
    storageBucket: 'autofore-app.appspot.com',
    measurementId: 'G-J0HYPSD222',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeBRCcCmQDPkD4bF9XhrqP5BkNBFYXyjk',
    appId: '1:525477025365:android:880e9a1bd5e32a66c826dc',
    messagingSenderId: '525477025365',
    projectId: 'autofore-app',
    storageBucket: 'autofore-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmBDwZBW99jWNEFjnGSqqkH4FQJbpwb3g',
    appId: '1:525477025365:ios:f9ce7f8593fc06cac826dc',
    messagingSenderId: '525477025365',
    projectId: 'autofore-app',
    storageBucket: 'autofore-app.appspot.com',
    iosBundleId: 'com.example.autofore',
  );
}
